version: '3.9'

services:
  producer-app:
    container_name: producer-app
    build:
      context: .
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management plugin port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"

volumes:
  rabbitmq_data:
    driver: local
